spring:
  jpa:
    show-sql: true # ?? ? sql ???? ???? ??? ??
    hibernate:
      ddl-auto: none # hibernate ? ???? ?????? ???? ???? ??? ?? ?? ??
    database-platform: org.hibernate.dialect.H2Dialect # ??? ???? jpa ? ???? ??????? ?? ? hibernate ?? ?? ? ?????? ???? ????? ???? ??

  sql:
    init:
      mode: always # ?? ?? sql ????? ?????
      platform: h2

  datasource:
    url: jdbc:h2:mem:development;MODE=MYSQL;DB_CLOSE_DELAY=-1 # h2 ???? ??? ???? ???? developement ??? mysql
    username: sa
    password:
    driverClassName: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console
